"""Kelompok 5 A081.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S-ZHy7BK8f7FJV9XkgU47Wv67KDWV0u3
"""

import numpy as np
import pandas as pd
from tabulate import tabulate

dataset = pd.read_csv('dataset.csv')

train_size = int(0.77 * len(dataset))
dataset_train = dataset.iloc[:train_size]
dataset_test = dataset.iloc[train_size:]

print("Data Training")
dataset_train

print("Data Testing")
dataset_test

print("\nInfo Dataset Training")
dataset_train.info()
print("\nInfo Dataset Training")
dataset_test.info()

if (dataset_train.empty == False):
    print("Data Training Tidak Ada Yang Kosong")
else:
    print("Data Training Ada Yang Kosong")

if (dataset_test.empty == False):
    print("Data Testing Tidak Ada Yang Kosong")
else:
    print("Data Testing Ada Yang Kosong")

data2 = dataset.iloc[:, :].values

attribute_counts = [0] * 170 

print("Atribut Untuk Data Training:")

# Iterate through dataset
for i in range(len(data2[:97])):  # Limit data to 97 rows
    if data2[i][17] == "Puas":
        attribute_counts[0] += 1
        for j, offset in zip(range(1, 17), range(2, 162, 10)):
            attribute_counts[offset] += 1 if data2[i][j] == "SB" else 0
            attribute_counts[offset + 2] += 1 if data2[i][j] == "B" else 0
            attribute_counts[offset + 4] += 1 if data2[i][j] == "CB" else 0
            attribute_counts[offset + 6] += 1 if data2[i][j] == "KB" else 0
            attribute_counts[offset + 8] += 1 if data2[i][j] == "TB" else 0
    else:
        attribute_counts[1] += 1
        for j, offset in zip(range(1, 17), range(3, 163, 10)):
            attribute_counts[offset] += 1 if data2[i][j] == "SB" else 0
            attribute_counts[offset + 2] += 1 if data2[i][j] == "B" else 0
            attribute_counts[offset + 4] += 1 if data2[i][j] == "CB" else 0
            attribute_counts[offset + 6] += 1 if data2[i][j] == "KB" else 0
            attribute_counts[offset + 8] += 1 if data2[i][j] == "TB" else 0

print(f"Diagnosa:\nPuas: {attribute_counts[0]}\nTidak Puas: {attribute_counts[1]}")

for j in range(1, 17):
    offset = (j - 1) * 10 + 2
    print(f"\nAtribut A{j}:\nSB Puas: {attribute_counts[offset]}\nSB Tidak Puas: {attribute_counts[offset + 1]}")
    print(f"B Puas: {attribute_counts[offset + 2]}\nB Tidak Puas: {attribute_counts[offset + 3]}")
    print(f"CB Puas: {attribute_counts[offset + 4]}\nCB Tidak Puas: {attribute_counts[offset + 5]}")
    print(f"KB Puas: {attribute_counts[offset + 6]}\nKB Tidak Puas: {attribute_counts[offset + 7]}")
    print(f"TB Puas: {attribute_counts[offset + 8]}\nTB Tidak Puas: {attribute_counts[offset + 9]}")

# Adjusting the name list to match the probabilities length
name = ["Puas", "Tidak Puas"] + [
    f"A{j}-{val}-{status}"
    for j in range(1, 17)
    for val in ["SB", "B", "CB", "KB", "TB"]
    for status in ["Puas", "Tidak Puas"]
]

# Ensure name and probabilities alignment without errors
if len(name) > len(probabilities):
    name = name[:len(probabilities)]
elif len(probabilities) > len(name):
    probabilities = probabilities[:len(name)]

# Organize results
probability_data = np.column_stack((name, probabilities))

# Display results
keys = ["Atribut", "Probabilitas"]
print("\nData Probabilitas:")
print(tabulate(probability_data, headers=keys, tablefmt="grid"))

# Split the dataset into training and testing
train_size = int(0.77 * len(dataset))
dataset_train = dataset.iloc[:train_size]
dataset_test = dataset.iloc[train_size:]

# Convert the dataset to a numpy array for processing
data = dataset.values

# Initialize counters for attributes and outcomes
attribute_counts = [0] * 170  # Adjusted to accommodate all attributes

# Process the training dataset for Naive Bayes calculations
for i in range(len(dataset_train)):
    if data[i][-1] == "Puas":
        attribute_counts[0] += 1
        for j, offset in zip(range(1, 17), range(2, 162, 10)):
            attribute_counts[offset] += 1 if data[i][j] == "SB" else 0
            attribute_counts[offset + 2] += 1 if data[i][j] == "B" else 0
            attribute_counts[offset + 4] += 1 if data[i][j] == "CB" else 0
            attribute_counts[offset + 6] += 1 if data[i][j] == "KB" else 0
            attribute_counts[offset + 8] += 1 if data[i][j] == "TB" else 0
    else:
        attribute_counts[1] += 1
        for j, offset in zip(range(1, 17), range(3, 163, 10)):
            attribute_counts[offset] += 1 if data[i][j] == "SB" else 0
            attribute_counts[offset + 2] += 1 if data[i][j] == "B" else 0
            attribute_counts[offset + 4] += 1 if data[i][j] == "CB" else 0
            attribute_counts[offset + 6] += 1 if data[i][j] == "KB" else 0
            attribute_counts[offset + 8] += 1 if data[i][j] == "TB" else 0

# Calculate probabilities for each attribute and class
probabilities = [count / len(dataset_train) for count in attribute_counts]

# Perform Naive Bayes prediction on the test dataset
keys = ["Hasil Aktual", "Hasil Prediksi Naive Bayes"]
dTest = dataset_test.iloc[:, 1:-1].values
yPredik = dataset_test.iloc[:, -1].values
yHasilNB = []

for i in range(len(dTest)):
    rPuas = probabilities[0]
    rTidakPuas = probabilities[1]

    for j, offset in zip(range(16), range(2, 162, 10)):
        if dTest[i][j] == "SB":
            rPuas *= probabilities[offset]
            rTidakPuas *= probabilities[offset + 1]
        elif dTest[i][j] == "B":
            rPuas *= probabilities[offset + 2]
            rTidakPuas *= probabilities[offset + 3]
        elif dTest[i][j] == "CB":
            rPuas *= probabilities[offset + 4]
            rTidakPuas *= probabilities[offset + 5]
        elif dTest[i][j] == "KB":
            rPuas *= probabilities[offset + 6]
            rTidakPuas *= probabilities[offset + 7]
        elif dTest[i][j] == "TB":
            rPuas *= probabilities[offset + 8]
            rTidakPuas *= probabilities[offset + 9]

    # Compare probabilities and classify
    yHasilNB.append("Puas" if rPuas > rTidakPuas else "Tidak Puas")

# Combine actual and predicted results for display
dHasilPredikDanNaiveBayes = np.column_stack((yPredik, yHasilNB))
print("\nHasil Prediksi dan Naive Bayes Untuk Data Testing:")
print(tabulate(dHasilPredikDanNaiveBayes, headers=keys, tablefmt="grid"))

# Calculate accuracy based on the prediction results
confusionMatrik = [0] * 4  # [TP, FP, FN, TN]

# Iterate through the prediction results and calculate confusion matrix values
for i in range(len(dHasilPredikDanNaiveBayes)):
    if dHasilPredikDanNaiveBayes[i][0] == "Puas" and dHasilPredikDanNaiveBayes[i][1] == "Puas":
        confusionMatrik[0] += 1  # True Positive (TP)
    elif dHasilPredikDanNaiveBayes[i][0] == "Puas" and dHasilPredikDanNaiveBayes[i][1] == "Tidak Puas":
        confusionMatrik[1] += 1  # False Negative (FN)
    elif dHasilPredikDanNaiveBayes[i][0] == "Tidak Puas" and dHasilPredikDanNaiveBayes[i][1] == "Puas":
        confusionMatrik[2] += 1  # False Positive (FP)
    else:
        confusionMatrik[3] += 1  # True Negative (TN)

# Display the confusion matrix values
print("TP:", confusionMatrik[0])
print("FP:", confusionMatrik[2])
print("FN:", confusionMatrik[1])
print("TN:", confusionMatrik[3])

# Calculate and display the accuracy
akurasi = (confusionMatrik[0] + confusionMatrik[3]) / len(dHasilPredikDanNaiveBayes)
print(f"Tingkat Akurasi: {akurasi * 100:.2f}%")

print("Mencoba Inputan Dari User")

# Input data dari pengguna
A1 = input("Masukkan Atribut A1 (SB/B/CB/KB/TB): ")
A2 = input("Masukkan Atribut A2 (SB/B/CB/KB/TB): ")
A3 = input("Masukkan Atribut A3 (SB/B/CB/KB/TB): ")
A4 = input("Masukkan Atribut A4 (SB/B/CB/KB/TB): ")
A5 = input("Masukkan Atribut A5 (SB/B/CB/KB/TB): ")
A6 = input("Masukkan Atribut A6 (SB/B/CB/KB/TB): ")
A7 = input("Masukkan Atribut A7 (SB/B/CB/KB/TB): ")
A8 = input("Masukkan Atribut A8 (SB/B/CB/KB/TB): ")
A9 = input("Masukkan Atribut A9 (SB/B/CB/KB/TB): ")
A10 = input("Masukkan Atribut A10 (SB/B/CB/KB/TB): ")
A11 = input("Masukkan Atribut A11 (SB/B/CB/KB/TB): ")
A12 = input("Masukkan Atribut A12 (SB/B/CB/KB/TB): ")
A13 = input("Masukkan Atribut A13 (SB/B/CB/KB/TB): ")
A14 = input("Masukkan Atribut A14 (SB/B/CB/KB/TB): ")
A15 = input("Masukkan Atribut A15 (SB/B/CB/KB/TB): ")
A16 = input("Masukkan Atribut A16 (SB/B/CB/KB/TB): ")

# Inisialisasi probabilitas
rPuas = probabilities[0]
rTidakPuas = probabilities[1]

# Kalkulasi probabilitas berdasarkan input
attributes = [A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16]

for j, offset in zip(range(16), range(2, 162, 10)):
    if attributes[j] == "SB":
        rPuas *= probabilities[offset]
        rTidakPuas *= probabilities[offset + 1]
    elif attributes[j] == "B":
        rPuas *= probabilities[offset + 2]
        rTidakPuas *= probabilities[offset + 3]
    elif attributes[j] == "CB":
        rPuas *= probabilities[offset + 4]
        rTidakPuas *= probabilities[offset + 5]
    elif attributes[j] == "KB":
        rPuas *= probabilities[offset + 6]
        rTidakPuas *= probabilities[offset + 7]
    elif attributes[j] == "TB":
        rPuas *= probabilities[offset + 8]
        rTidakPuas *= probabilities[offset + 9]

# Prediksi hasil berdasarkan probabilitas
print("\nHasil Prediksi Naive Bayes:")
if rPuas > rTidakPuas:
    print("PUAS")
else:
    print("TIDAK PUAS")

